### ISSUE TITLE
[Feature] Add 'Blank' System

### ISSUE THREAD

**Issue by acdervis** [evewspace/eve-wspace#106]
Usage: When adding a system, type a system name(ex: Blank) to create a system that doesn't exist in Anoikis or New Eden, to be corrected later.

Intended Usage(s): 1)When scouting a system scanners may be unwilling to scout an EOL hole, but something may come through and knowing there's an unscouted system may prove useful.
2)Ability to create friendly system name prior to bookmarking without misinforming other users.

**Comment by ij-watson** [comment]
The best way to represent this would be by creating a wormhole with the 'System Name' set to the sig ID. Validation could check for the presence of a pattern matching '[A-Z]{3}-[0-9]{3}' (e.g. ABC-123) and bypass matching against a known system name.

**Comment by dagoaty** [comment]
The best way to represent this would be by creating a wormhole with the 'System Name' set to the sig ID. Validation could check for the presence of a pattern matching '[A-Z]{3}-[0-9]{3}' (e.g. ABC-123) and bypass matching against a known system name.
