### ISSUE TITLE
Error when attempting to delete a user

### ISSUE THREAD

**Issue by acdervis** [evewspace/eve-wspace#116]
OperationalError: (1054, "Unknown column 'POS_posapplication_residents.ewsuser_id' in 'where clause'")

I've checked and the column indeed doesn't exist. There's a similar column called 'user_id' in the same table. I have run migrations.

**Comment by marbindrakon** [comment]
That one must have been missed int he migrations. Deleting users probably shouldn't be supported given the number of relations to the user table. I'd recommend setting them to inactive and renaming the username if you need to re-use it.
