### ISSUE TITLE
[SiteTraker] Wrong calculated points at pending site.

### ISSUE THREAD

**Issue by neosilver-gk** [evewspace/eve-wspace#131]
We find out that site claims are wrong calculated if a member joint after a claim and pending that claim. Than everyone gets or still kept that amount of point you get with less members in a fleet. 
An extrem example: boss and two others opens a fleet. Claim an escalation and gets many points. Now 10 more members joining and pending that escalation. Everyone gets that big amount of points.

Would be good to change that.

**Comment by neosilver-gk** [comment]
@marbindrakon is this what SSC wanted that it works or did you just miss to read my issue?

**Comment by marbindrakon** [comment]
neosilver, this will be fixed when the SiteTracker is re-written.

**Comment by neosilver-gk** [comment]
I thought to change some code would be enough (see below), but the SiteTracker not changed. It is not even caused a different reaction.

Changes in SiteTracker/view.py:

def claim_site(request, fleetID, siteID, memberID):
....
else:
    if fleet.current_boss == request.user:
        new_fleetsize = site.fleetsize + 1
        x = float(get_config("ST_SIZE_WEIGHT", None).value)
        n = new_fleetsize
        if x > 1:
            weight_factor = x / float(n + (x - 1))
        else:
            weight_factor = float(1)

        site.fleetsize = new_fleetsize
        site.weighted_points = site.raw_points * weight_factor
        site.save()
....

probably I'm doing pretty much everything wrong

**Comment by neosilver-gk** [comment]
I have found the code that causes the values. In the pull request # 205 I changed the code.
