### ISSUE TITLE
[Feature] Add support for CCP SSO

### ISSUE THREAD

**Issue by dagoaty** [evewspace/eve-wspace#150]
I would like to  be able to grant access to my mapper by allowing users to log in with their EVE credentials, taking advantage of the [CCP Single Sign-On feature](https://developers.eveonline.com/resource/single-sign-on). Once a character has logged in this way I should be able to add them to groups as normal. Additionally it would be good to auto-add logins to a group, or groups, based on their corp and/or alliance. This is similar to how the registration code for a group currently works.

**Comment by Zumochi** [comment]
:+1: but I don't know how feasible this is in the foreseeable future.

**Comment by marbindrakon** [comment]
This was the motivation for changing the license to Apache, I just haven't gotten it done yet.

**Comment by tyler274** [comment]
Python-social-auth http://psa.matiasaguirre.net/docs/configuration/django.html already has support for the eve-sso and has a django integration.

**Comment by marbindrakon** [comment]
This is high on the priority list after the django 1.8 migration. Registration will likely not be included in the initial pass as that will require logic on what types of users to allow (corporation, alliance, whitelist, etc).

**Comment by tyler274** [comment]
logic could be something along the lines of automatically adding corp/alliance/etc X to Y group(s).

**Comment by Yracka** [comment]
:+1:

**Comment by raphendyr** [comment]
I'm interested to get this implemented. I'll check if I have time to look into this too in near future.

With SSO auth we should be able to revoke access to the mapper when a member leaves a corp. Basically set of automatic groups would be nice.

**Comment by raphendyr** [comment]
Note to self (and maybe others): `If all you need is corp you can also get that from CREST: https://crest-tq.eveonline.com/characters/<char_id>/` probably easiest way to get corp info for permissions.

**Comment by raphendyr** [comment]
Work in progress version at https://github.com/raphendyr/eve-wspace/tree/feature/crest_wip if someone is interested to follow it. Comments are welcome in tweetfleet slack or github.

**Comment by raphendyr** [comment]
I'm again working on this and I expect get this in working condition on this week.

**Comment by Maarten28** [comment]
Refer to #162
