### ISSUE TITLE
Django 1.6 unsupported

### ISSUE THREAD

**Issue by Zumochi** [evewspace/eve-wspace#153]
Since April 1st, extended support for Django 1.6 has ended.
With that, it might be a good idea to start looking to migrate to Django 1.8, the next LTS release, supported until at least April 2018.

I'll personally see if I can have a go at this soonish to also learn more about Django and Python in general :smiley: but don't expect much as my knowledge and time is limited :grin:

Links to deprecated functions:
[Django Deprecation Timeline](https://docs.djangoproject.com/en/1.8/internals/deprecation/)
[Django 1.7](https://docs.djangoproject.com/en/1.8/releases/1.7/#features-deprecated-in-1-7)
[Django 1.8](https://docs.djangoproject.com/en/1.8/releases/1.8/#features-deprecated-in-1-8)

**Comment by marbindrakon** [comment]
I will be targeting 1.8 for the next release.
