### ISSUE TITLE
Setup eve-wspace under sub-directory of my domain 

### ISSUE THREAD

**Issue by neosilver-gk** [evewspace/eve-wspace#159]
Hi, 
I'am now looking and testing about 2 days to get eve-wspace working under a sub-directory of my domain. I can't finde a solution.

I would like to secure my domain and all web-apps with ssl. The cheapest solution is to use a StartSSL certificate without wildcard. Therefor I have to set all Apps under a sub-directory. Is there a simple way to do this, or do I have to view the whole code?

Pleas help me and add this to the description. I can imagine that I'm not the only one who need this.

**Comment by nyrocron** [comment]
This not really something specific to this application and should be handled by whatever you use to serve your WSGI apps.

The way I run some django sites is that I run them with gunicorn on a local socket and nginx facing the web. nginx can handle SSL and passing the required headers to django/gunicorn.

This should still mostly apply: http://stackoverflow.com/questions/8133063/how-to-deploy-django-under-a-suburl-behind-nginx

**Comment by marbindrakon** [comment]
Unfortunately, the javascript parts of EWS make assumptions about where things are being served. To make it work, you would need to edit the files in */static/js to include your prefix on the AJAX calls.

I'll try to get prefix support into the next release.

**Comment by nyrocron** [comment]
You could still work around this by rewriting the relevant URLs but it'd require some more configuration and not using these subdirectories for anything else.

**Comment by Zumochi** [comment]
@neosilver-gk with StartSSL you have two domain names: yourdomain.com and anything.yourdomain.com.

So, you can make yourdomain.com your main website and then map.yourdomain.com the mapping tool.

If you don't want that, you can still do the above by rewriting request URLs, although that might be a bit too much work for what it's worth (not 100% sure, it might be easier than it seems :wink: )
