### ISSUE TITLE
Looking to discard some data

### ISSUE THREAD

**Issue by acdervis** [evewspace/eve-wspace#172]
I may be migrating an install soon. It's been used a lot over the past few years.

I was wondering if I could drop some data while keeping the intel such as POS data. Especially useful would be dropping users. I don't know where to start.

**Comment by Zumochi** [comment]
This is something I'd be interested in as well.
Planning to migrate to a new server this summer, if possible with a clean database.
:+1:

**Comment by marbindrakon** [comment]
You should be able to keep just about anything depending on how involved you want to make the migration. Out of the box, you should be able to dump anything that doesn't have a direct relation to EWSUser using the ./manage.py dumpdata command.

If it does have a relation to user, you may have to make a migration user on the new install and tie all of the records to them.

**Comment by acdervis** [comment]
For the sake of documenting the outcome: I ended up transferring the pos_pos, core_corporation, core_alliance tables and map_system.info, map_system.occupied columns.

The first three can just be copied over while disabling foreign key checks. The last two require checking for system_id and then updating the column field, especially if you have a different staticdump like I did.
