### ISSUE TITLE
Bulk import marks signatures as scanned

### ISSUE THREAD

**Issue by Zumochi** [evewspace/eve-wspace#182]
Bulk import immediately marks signatures as being scanned.

Previously,  they'd be marked as "Not yet scanned", which makes more sense.

Perhaps check if the type or info fields are set, if true mark them as scanned, if false, not scanned.

**Comment by Yracka** [comment]
https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png

**Comment by Maarten28** [comment]
Fixed in #219
