### ISSUE TITLE
Bulk import scrolls up on submit, breaking scanning workflow

### ISSUE THREAD

**Issue by nyrocron** [evewspace/eve-wspace#185]
When clicking the bulk import button the whole page scrolls up, this is very annoying when using the functionality frequently to update sigs.

Probably needs some change in how the form works.

**Comment by Maarten28** [comment]
If you let the form go to any html anchor which does not exist (#ThisDoesNotExist vs #) it should fix it. Not the cleanest way, but it works. Default behaviour for # is to move it to the top of the screen.

**Comment by nyrocron** [comment]
Working on it at the moment, calling preventDefault() (of jQuery) on the click event of the button seems to do it. Will have a pull request up soon.
