### ISSUE TITLE
[question] add wormhole class in wormholestatics.json

### ISSUE THREAD

**Issue by wimmuskee** [evewspace/eve-wspace#188]
hi guys,

I've been using your wormholestatics.json as an input for all wormhole systems for my own site. Currently, I have to connect it to the Static Data Export mapLocationWormholeClasses table to determine the actual class of a system. 
As you might know, the class of each wormhole is connected with the regionID. Except the new Drifter wormholes, they are connected with the solarSystemID.

I don't know exactly how you are using the wormholestatics.json in your tool, but wouldn't it be more efficient to premake the json with the wormhole class?

If you like, I can provide you a new wormholestatics.json with the class.

**Comment by marbindrakon** [comment]
The buildsystemdata command handles the sysclass information as well as creating the KSystem and WSystem records. If I were to do this, I'd eliminate wormholestatics.json and create ksystem and wsystem fixtures. That would eliminate the need to use the buildsystemdata tool to process the SDE data.

**Comment by wimmuskee** [comment]
Right, you have to build the data for the Kspace systems anyway for your tool to function outside Wspace. The wormholestatics.json fixture is just an addition to the database information. 

I guess it would be only a slight improvement (and you probably have more pressing stories to solve). 

Well, closing the issue, but will keep watching this repo, thx for replying.
