### ISSUE TITLE
Some help?

### ISSUE THREAD

**Issue by Broderick-Gibbons** [evewspace/eve-wspace#189]
Can anyone here help me with an auth API open source? I don't know python or anything so pretty much need someone to code and I let them know what exactly I need? Thanks

**Comment by nyrocron** [comment]
This is not the right place for this.

**Comment by Broderick-Gibbons** [comment]
then where is the right place hmm???

**Comment by marbindrakon** [comment]
If you're looking for someone to write code for you, you might try the Eve-O forums or /r/evetech on reddit.

**Comment by Broderick-Gibbons** [comment]
thanks for the advice! 


     On Monday, July 20, 2015 12:03 PM, Andrew Austin <notifications@github.com> wrote:
   

 If you're looking for someone to write code for you, you might try the Eve-O forums or /r/evetech on reddit.—
