### ISSUE TITLE
Collapsed systems keep displaying connection line.

### ISSUE THREAD

**Issue by acdervis** [evewspace/eve-wspace#191]
![image](http://i.imgur.com/UVAE0Zn.png)

The general setting "Show Collapsed Systems" doesn't seem to do anything either.

**Comment by nyrocron** [comment]
Doesn't happen for me.

**Comment by Maarten28** [comment]
This is a setting under Settings -> Map settings.

**Comment by acdervis** [comment]
I've realized that my personal settings had "Show Collapsed Connections" selected. Is there a way to set a default value for this for newly registering users?

**Comment by marbindrakon** [comment]
You can change the system defaults under the Map Admin tab in settings. Those will apply to any user who hasn't set personal settings.

**Comment by acdervis** [comment]
Thanks, after asking somebody that hadn't fiddled around with their settings all seems well.

As a final followup: Is there a way to force this setting globally and disabled the personal setting?

**Comment by marbindrakon** [comment]
There isn't a built-in way to do that, but you could write a script to do it and just add it to your crontab. You would just want to delete any ConfigEntry rows where user isn't null and the key is the setting you want to enforce.
