### ISSUE TITLE
Error when entering new POS into mapper

### ISSUE THREAD

**Issue by TychoLoor** [evewspace/eve-wspace#196]
I've been getting errors when trying to enter new POSs into the mapper under the starbases tab. Below is a copy of the error report I just got. A fellow pilot in corp is not getting this error and is able to enter them without issues.

MultipleObjectsReturned at /pos/109/add/ get() returned more than one Type -- it returned 2! Request Method: POST Request URL: http://templeofbob.evewspace.com/pos/109/add/ Django Version: 1.6.1 Python Executable: /usr/bin/python Python Version: 2.7.5 Python Path: ['/home/maptool/eve-wspace/evewspace', '/home/maptool/eve-wspace/evewspace/evewspace', '/usr/bin', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib/python2.7/site-packages'] Server time: Tue, 11 Aug 2015 21:46:06 +0000 Installed Applications: ('django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.sites', 'django.contrib.messages', 'django.contrib.staticfiles', 'django.contrib.humanize', 'core', 'Map', 'POS', 'Alerts', 'Jabber', 'SiteTracker', 'API', 'Slack', 'account', 'eveigb', 'search', 'djcelery', 'south') Installed Middleware: ('django.middleware.common.CommonMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'eveigb.middleware.IGBMiddleware') Traceback: File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response 114. response = wrapped_callback(request, *callback_args, **callback_kwargs) File "/usr/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view 22. return view_func(request, *args, **kwargs) File "/home/maptool/eve-wspace/evewspace/POS/views.py" in add_pos 217. pos.fit_from_iterable(fittings) File "/home/maptool/eve-wspace/evewspace/POS/models.py" in fit_from_iterable 178. item_type = Type.objects.get(name=row[1]) File "/usr/lib/python2.7/site-packages/django/db/models/manager.py" in get 151. return self.get_queryset().get(*args, **kwargs) File "/usr/lib/python2.7/site-packages/django/db/models/query.py" in get 310. (self.model._meta.object_name, num)) Exception Type: MultipleObjectsReturned at /pos/109/add/ Exception Value: get() returned more than one Type -- it returned 2!

**Comment by Zumochi** [comment]
Can you put that in a code block (surround by three backticks (`)) or put it on pastebin or something?

**Comment by marbindrakon** [comment]
I snipped the bulk to the output from the issue. The root cause was there being two items in the SDE with the exact name 'Drug Lab'. The POS fitting importer will need to be changed to handle edge cases like that (probably by ignoring the problematic module).
