### ISSUE TITLE
[Issue] Adding POSes with Drug Labs Fails

### ISSUE THREAD

**Issue by AceMgy** [evewspace/eve-wspace#199]
Reproduction:  Use this pastebin of a specific pos http://pastebin.com/jDuDHrEj
Remove the drug lab entry (for convenience http://pastebin.com/FHyRmRGt )
Then it works.

Pastebin of the error it spits out http://pastebin.com/3AQfX5Ha

**Comment by Zumochi** [comment]
Fairly sure this is a duplicate of #196

**Comment by marbindrakon** [comment]
The instance you're using wasn't updated to the latest build. It should be fixed now.
