### ISSUE TITLE
Move CCP legal notice to About page

### ISSUE THREAD

**Issue by andrewd18** [evewspace/eve-wspace#208]
The text at the bottom of each map page is distracting. Can we have it moved to a different page, such as an "About EVE-WSpace" page?

**Comment by marbindrakon** [comment]
I think this can be done now under the new dev license. The older fansite toolkit license required that (rather verbose) notice to appear on any page that an image or other CCP copyrighted material appeared on.

The required text from the new license is "© 2014 CCP hf. All rights reserved. "EVE", "EVE Online", "CCP", and all related logos and images are trademarks or registered trademarks of CCP hf."

**Comment by Maarten28** [comment]
This has been only on the first page for a while now, therefore closing this issue.
