### ISSUE TITLE
In-game browser functionality not working

### ISSUE THREAD

**Issue by andrewmunro** [evewspace/eve-wspace#212]
I've made by build using the docker file available, tried both the master and development branch. In both builds, the mapper functions fine except that the eve in-game browser will not update the mapper.

With Silent IGB Mapping on, no wormholes are added to the mapper when jumping through them from the root system. Also, I've noticed that the pilot count does not work, always showing that 0 pilots are in the system (this has been tested with multiple eve clients).

I have no idea how to go about debugging this as I have no knowledge of how the in game browser communication actually works (I assume some JS API but I can't see any developer tools). Can anyone confirm if they are having the same issues or if it is something to do with my setup?

**Comment by Zumochi** [comment]
Are the celery and redis-server services running?

**Comment by andrewmunro** [comment]
Supervisor reports that rabbitmq, nginx, mysql, gunicorn and celeryd are all running fine. I wasn't aware this project required redis, I assume you meant rabbit.

I also don't seem to have any logs anywhere. Are they enabled by default, and if so, where can I find them. 

The eve-wspace/gunicorn directory does not exist.

**Comment by Zumochi** [comment]
You're right, sorry, it's rabbitmq, not redis.

If you're on a Debian-based system supervisor should put logs in /var/log/supervisor.

I meant the eve-wspace or gunicorn logs, not directories :)

**Comment by marbindrakon** [comment]
Can you make sure memcached is up and running? Real-time tracking caches locations of players there instead of the database.

**Comment by andrewmunro** [comment]
@marbindrakon Wooo fixed it! Yup you were right, the memcached service was not running. Someone should stick a line in the Dockerfile to start it or move it to the supervisor.
