### ISSUE TITLE
Load images.eveonline.com content over https

### ISSUE THREAD

**Issue by andrewd18** [evewspace/eve-wspace#221]
The images loaded from CCP are loaded using http:// instead of https://.  This creates a "Connection is Not Secure" warning on some browsers.

The images should either be brought in as https or correspond to the level of security the user signed in with (are there even people who use it w/o https?!?).

**Comment by Maarten28** [comment]
Done.

https://github.com/Maarten28/eve-wspace/commit/0ee53864fbf8a7f923277ed086cc9b432cc3260a (part of the Django 1.8 PR)
