### ISSUE TITLE
[questions] get warnings after upgrade

### ISSUE THREAD

**Issue by neosilver-gk** [evewspace/eve-wspace#233]
Hi, after I upgraded eve-wspace I get some  "OneToOne is better than ManyToMany" warnings. They appear when I make my migration  (./manage.py migrate --fake) as well as when I start the server  (./manage.py runserver 0.0.0.0:8000). How to solve this and how to migrate from a build 3 month ago? 

Some additional: is there still a possibility to get real time help e.g. IRC?

**Comment by Maarten28** [comment]
https://github.com/evewspace/eve-wspace/pull/219#issuecomment-167875224

The warnings itself do not matter, the install should still work. You should however follow a similar upgrade path compared the one above.

**Comment by Zumochi** [comment]
Besides this, I hope you're using `./manage.py runserver` for testing/development purposes only. :smile:

**Comment by neosilver-gk** [comment]
Of course, I use it only for testing. I have now changed the models so that the warnings disappear. Pull request follows.
