### ISSUE TITLE
[current master] Add system doesn't appear to set wormhole type or status

### ISSUE THREAD

**Issue by raphendyr** [evewspace/eve-wspace#240]
New UI doesn't appear to handle add system window properly. I try to allocate time to look into this, as it's quite big thing for us.

Anycase, wanted to let others know.

**Comment by Zumochi** [comment]
Interesting as it seems to work for me. So you get the popup, fill in type/status etc and it remains k162?

**Comment by raphendyr** [comment]
Exactly. Might be that I broke something with my local "disable reddit, rss" patch. I think its specially the automatic popup that comes when going trough wormhole as the manual "add system" gets correct colors fot normal, first shrink etc.

**Comment by raphendyr** [comment]
Also, the UI is different on my chomium and IGB. Jsut noticed when tested this.

edit: this was because the width of the IGB. I have it smaller than expected it appears.

**Comment by raphendyr** [comment]
Yeps. The "options > add system" works, but not the one that poups when you enter new system.

**Comment by raphendyr** [comment]
Reading the code... It appears that automatic dialog is handled a bit differently. The `update/` call returns html for the dialog. It returns tempalte `templates/igb_system_add_dialog.html` instead of the manual `templates/add_system_box.html`.

I think we a) should return just info "show add sytem dialog with system name foobar" and then on client call the addsystem function or b) return the same template with value for the system name.

Anycase having 2 different templates for same data is a bit error prone.

**Comment by raphendyr** [comment]
Ok. Even though the layout is broken this might not be related to that. Apparently if the dialog window is moved, it wil lreset _all_ of the settings, thus anything changed will be reseted. Interesting bug.

**Comment by Maarten28** [comment]
The PR is in develop now, so should be fixed now.
