### ISSUE TITLE
Static files not being pulled (403 Forbidden)

### ISSUE THREAD

**Issue by literallybased** [evewspace/eve-wspace#247]
Settings.py: http://pastebin.com/tczzpqKW
local_settings.py: http://pastebin.com/xqtHAA4L
gunicorn: http://pastebin.com/KMsvZPyU
apache evewspace.conf: http://pastebin.com/ah6i5uJj

error: http://prntscr.com/aqm193

Set all dirs 777 for testing purposes, still no change.
`sudo chmod -R 777 /home/`

Static files load when using './manage.py runserver 0.0.0.0:8000' and accessing the server from port 8000. Loading site through the apache port 80 still results in forbidden.

**Comment by marbindrakon** [comment]
What distro are you running this on?

**Comment by raphendyr** [comment]
Some kind of apache configuration issue. Check supporting config files under `/etc/{apache2,htttpd}/conf.d/` or similar paths. Please comment when you or someone finds a fix so I can update the documentation.
