### ISSUE TITLE
IGB spamming mapper

### ISSUE THREAD

**Issue by hybrid1969** [evewspace/eve-wspace#249]
Over the past couple of days our mapper has suddenly slowed down for no apparent reason and so the first place I checked was the Apache logs which are now hitting 40mb+ per day??

I have looked through and it looks like the IGB is spamming the mapper causing the slow down.

Any clues as to what be causing this all of a sudden.

I have checked all the IP's and can rule out deliberate attacks.

**Comment by quinnjr** [comment]
Can you put the logs up in a pastebin or gist?

**Comment by bewbaloo** [comment]
I am having the same issue.  I'll try and snag logs.

Edit: logs of outgoing traffic for abour ~1.5 minutes http://pastebin.com/RgW4jkWL

**Comment by marbindrakon** [comment]
The traffic you posted looks correct (assuming default 5s update poll and 15s auto-refresh from one client). If you're seeing a sudden slowdown though, you might check that memcached is running and try flushing the cache. Also, check to make sure you aren't running in DEBUG mode as that can introduce a memory leak from the SQL profiling data being stored.

**Comment by hybrid1969** [comment]
We were not running memcache for some reason and this has been corrected.

Also while digging for the debug setting, which i couldn't find so can only presume we are not using debug mode. I discovered our SSH connection was being hammered by china and russia, ACL now changed and now resolved.

If your seeing slowdowns check ALL your logs as it may not be anything to do with the mapper itself.
