### ISSUE TITLE
Can not add new POSes

### ISSUE THREAD

**Issue by bewbaloo** [evewspace/eve-wspace#250]
Whenever I try and add a new POS since the latest EVE update (either auto or manual), I get this error:

http://pastebin.com/0uLiaXdd

Thanks for any help!

**Comment by quinnjr** [comment]
Have you updated the EWS database with the most recent SDE since the latest update?

And can you re-post that bin with formatting? The lack of lines makes it painful to read through.

**Comment by bewbaloo** [comment]
@illuser I copied it out of the browser window just as it was outputted; I'm not familiar enough with python to parse that out.

**Comment by quinnjr** [comment]
Are you the one running the ews app you're using? If so, can you copy the error logs which were generated server-side?

**Comment by marbindrakon** [comment]
From the traceback you posted, check that RabbitMQ and Celery are running. It appears that kombu was unable to connect to the RabbtiMQ port (Connection refused exception).

**Comment by bewbaloo** [comment]
RabbitMQ had indeed crashed because the ec2 ran out of memory.  Reconfiguring some processes freed the memory up and got it working again.

**Comment by marbindrakon** [comment]
Good to hear.

Make sure you change DEBUG set to False in your local_settings.py file. Running with DEBUG=True will cause the async worker to leak memory due to SQL query caching for debugging purposes.
