### ISSUE TITLE
Internal Server Error: Editing deleted system

### ISSUE THREAD

**Issue by acdervis** [evewspace/eve-wspace#256]
I have our server configured to send me error reports by e-mail. It's quite helpful when there's a hiccup with the DB or we have high load etc. Unfortunately, many cases aren't handled and the code throws a 500, spamming my inbox.

One of the more frequent culprits is the Map.views file. If a user deletes a system and another user tries to edit it before they get a refresh, the resulting query fails doesn't return anything and the edit throws an error. Here's the traceback: https://gist.github.com/acdervis/1352769338dad52348b9eaf8469a8f80

Could we make this fail silently perhaps? It doesn't seem like an exceptional case and I don't see any value in generating an error.

**Comment by Maarten28** [comment]
I believe this is fixed now, therefore I'll close it.
