### ISSUE TITLE
[Suggestion]  ESI API Support

### ISSUE THREAD

**Issue by EvilGrinUK** [evewspace/eve-wspace#261]
CCP has developed a new API called ESI to (eventually) replace Crest and the XML API.

https://community.eveonline.com/news/dev-blogs/introducing-esi/

Interactive documentation is available at:

https://esi.tech.ccp.is/latest/

**Comment by nyrocron** [comment]
Certainly looks interesting and using it is probably a good idea.

**Comment by Maarten28** [comment]
Refer to #162
