### ISSUE TITLE
B520 MIssing from Database

### ISSUE THREAD

**Issue by marbindrakon** [evewspace/eve-wspace#97]
C6 > High

Freighter capable

**Comment by Zumochi** [comment]
Is this fixed yet? If not, I'll have a look.

On another note, maybe there should be a guideline on how to report missing wormhole types or wrong data?
e.g.
Missing: Type - Source : Destination
Wrong mass: Type - current value : fixed value

**Comment by nyrocron** [comment]
Is this still an issue?

**Comment by wimmuskee** [comment]
The B520 is not in the https://github.com/evewspace/eve-wspace/blob/develop/evewspace/Map/fixtures/wormholetypes.json

Jump mass for the B041 should be 1.000.000?

**Comment by neosilver-gk** [comment]
I find the http://www.ellatha.com/eve/wormholelist.asp data correct and would control all 90 values of the wormhole types. But I'll only do if you are of the opinion that the values ​​are correct.
